
try:
    print(x)

except:
    print("An eror occurred")

finally:
    print("Success")

try :
    num1 = 20
    num2 = 2
    print(num1 / num2)
except :
    print("An error occured")
